services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules               # ← TO dodaje ochronę node_modules
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "3000:3000"
    depends_on:
      - backend