import type { Stay, UserData } from "@/lib/types"

// Zmockowany profil - używany tylko jako fallback gdy API nie jest dostępne
export const mockUserProfile: UserData = {
  id: "guest1",
  name: "Jan Kowalski",
  email: "jan.kowalski@example.com",
  role: "guest",
  isActive: true,
  joinedAt: "2023-05-15T00:00:00Z",
  avatarUrl: "/placeholder.svg?height=100&width=100",
  bookings: 3,
}

export const mockLandlordStays: Stay[] = [
  {
    id: "ls1",
    propertyName: "Mountain View Cabin",
    propertyType: "Cabin",
    location: "Aspen, Colorado",
    checkIn: "2023-11-15",
    checkOut: "2023-11-20",
    nights: 5,
    guestName: "John Smith",
    guestImageUrl: "/placeholder.svg?height=40&width=40",
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.9,
    status: "completed",
  },
  {
    id: "ls2",
    propertyName: "Beachfront Villa",
    propertyType: "Villa",
    location: "Malibu, California",
    checkIn: "2023-12-05",
    checkOut: "2023-12-12",
    nights: 7,
    guestName: "Emma Johnson",
    guestImageUrl: "/placeholder.svg?height=40&width=40",
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.8,
    status: "completed",
  },
  {
    id: "ls3",
    propertyName: "Downtown Loft",
    propertyType: "Apartment",
    location: "New York, NY",
    checkIn: "2024-01-10",
    checkOut: "2024-01-15",
    nights: 5,
    guestName: "Michael Brown",
    guestImageUrl: "/placeholder.svg?height=40&width=40",
    imageUrl: "/placeholder.svg?height=300&width=400",
    status: "upcoming",
  },
  {
    id: "ls4",
    propertyName: "Lakeside Cottage",
    propertyType: "Cottage",
    location: "Lake Tahoe, Nevada",
    checkIn: "2024-02-01",
    checkOut: "2024-02-05",
    nights: 4,
    guestName: "Sarah Wilson",
    guestImageUrl: "/placeholder.svg?height=40&width=40",
    imageUrl: "/placeholder.svg?height=300&width=400",
    status: "upcoming",
  },
]

export const mockGuestStays: Stay[] = [
  {
    id: "gs1",
    propertyName: "Luxury Penthouse",
    propertyType: "Apartment",
    location: "Miami, Florida",
    checkIn: "2023-10-20",
    checkOut: "2023-10-25",
    nights: 5,
    hostName: "David Miller",
    hostImageUrl: "/placeholder.svg?height=40&width=40",
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 5.0,
    status: "completed",
  },
  {
    id: "gs2",
    propertyName: "Cozy Ski Chalet",
    propertyType: "Chalet",
    location: "Park City, Utah",
    checkIn: "2023-12-15",
    checkOut: "2023-12-22",
    nights: 7,
    hostName: "Jennifer Taylor",
    hostImageUrl: "/placeholder.svg?height=40&width=40",
    imageUrl: "/placeholder.svg?height=300&width=400",
    rating: 4.7,
    status: "completed",
  },
  {
    id: "gs3",
    propertyName: "Historic Brownstone",
    propertyType: "House",
    location: "Boston, Massachusetts",
    checkIn: "2024-03-05",
    checkOut: "2024-03-10",
    nights: 5,
    hostName: "Robert Anderson",
    hostImageUrl: "/placeholder.svg?height=40&width=40",
    imageUrl: "/placeholder.svg?height=300&width=400",
    status: "upcoming",
  },
]

export const mockUsers: UserData[] = [
  {
    id: "admin1",
    name: "Admin User",
    email: "admin@example.com",
    role: "admin",
    isActive: true,
    joinedAt: "2022-01-01T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "landlord1",
    name: "David Miller",
    email: "david@example.com",
    role: "landlord",
    isActive: true,
    joinedAt: "2022-03-15T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    properties: 3,
  },
  {
    id: "landlord2",
    name: "Jennifer Taylor",
    email: "jennifer@example.com",
    role: "landlord",
    isActive: true,
    joinedAt: "2022-05-20T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    properties: 2,
  },
  {
    id: "guest1",
    name: "John Smith",
    email: "john@example.com",
    role: "guest",
    isActive: true,
    joinedAt: "2022-02-10T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    bookings: 5,
  },
  {
    id: "guest2",
    name: "Emma Johnson",
    email: "emma@example.com",
    role: "guest",
    isActive: true,
    joinedAt: "2022-04-05T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    bookings: 3,
  },
  {
    id: "guest3",
    name: "Michael Brown",
    email: "michael@example.com",
    role: "guest",
    isActive: true,
    joinedAt: "2022-06-18T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    bookings: 2,
  },
  {
    id: "guest4",
    name: "Sarah Wilson",
    email: "sarah@example.com",
    role: "guest",
    isActive: false,
    joinedAt: "2022-07-22T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    bookings: 1,
  },
  {
    id: "landlord3",
    name: "Robert Anderson",
    email: "robert@example.com",
    role: "landlord",
    isActive: true,
    joinedAt: "2022-08-30T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    properties: 1,
  },
  {
    id: "guest5",
    name: "Lisa Thompson",
    email: "lisa@example.com",
    role: "guest",
    isActive: true,
    joinedAt: "2022-09-15T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    bookings: 4,
  },
  {
    id: "landlord4",
    name: "James Wilson",
    email: "james@example.com",
    role: "landlord",
    isActive: false,
    joinedAt: "2022-10-05T00:00:00Z",
    avatarUrl: "/placeholder.svg?height=40&width=40",
    properties: 2,
  },
]
